[features]
seeds = false
skip-lint = false

[programs.localnet]
christmas = "B2ejsK7m3eYPerru92hS73Gx7sQ7J83DKoLHGwn6pg5v"

[registry]
# url = "https://api.apr.dev"
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/Users/benjaminhon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_account_creation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_account_creation.ts"
