[features]
seeds = false
skip-lint = false
[programs.localnet]
christmas = "CM12BMd4GNixByaF4mrGwgptJMhuRMZbZNF9gnYSsSpd"

[registry]
# url = "https://api.apr.dev"
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/Users/benjaminhon/Developer/christmas/id_local.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
