[features]
seeds = false
skip-lint = false

[programs.localnet]
christmas = "B2ejsK7m3eYPerru92hS73Gx7sQ7J83DKoLHGwn6pg5v"

[registry]
# url = "https://api.apr.dev"
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/Users/benjaminhon/.config/solana/id.json"

[scripts]
# anchor test --skip-local-validator
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# anchor run test_happy -- --skip-local-validator
test_happy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_happy.ts"
# anchor run test_unhappy -- --skip-local-validator
test_unhappy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_unhappy.ts"
# anchor run test_utils -- --skip-local-validator
test_utils = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_utils.ts"
