version: "3"

services:
    minio:
        image: docker.io/bitnami/minio:2022
        ports:
            - "9000:9000"
            - "9001:9001" # webserver at http://localhost:9001
        networks:
            - minionetwork
        volumes:
            - "minio_data:/data"
        environment:
            - MINIO_ROOT_USER=user # development only
            - MINIO_ROOT_PASSWORD=password # development only
            - MINIO_DEFAULT_BUCKETS=bucket # development only

    redis-stack-svc:
        image: redis/redis-stack:latest
        environment:
            - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"
            - "8001:8001" # redis insight at http://localhost:8001

networks:
    minionetwork:
        driver: bridge

volumes:
    minio_data:
        driver: local
    redis_data:
        driver: local
