version: "3"

services:
    minio:
        image: docker.io/bitnami/minio:2022
        ports:
            - "9000:9000"
            - "9001:9001" # webserver at http://localhost:9001
        networks:
            - minionetwork
        volumes:
            - "minio_data:/data"
        environment:
            - MINIO_ROOT_USER=user # development only
            - MINIO_ROOT_PASSWORD=password # development only
            - MINIO_DEFAULT_BUCKETS=bucket # development only

networks:
    minionetwork:
        driver: bridge

volumes:
    minio_data:
        driver: local
