export const DEFAULT_GEOHASH_PRECISION = 6;

export const COUNTRY_DETAILS: { [countryCode: string]: [string, string] } = {
    "@@@": ["@@@", "@@@"], // Reserved for game world
    AF: ["AFG", "Afghanistan"],
    AFG: ["AFG", "Afghanistan"],
    AL: ["ALB", "Albania"],
    ALB: ["ALB", "Albania"],
    DZ: ["DZA", "Algeria"],
    DZA: ["DZA", "Algeria"],
    AS: ["ASM", "American Samoa"],
    ASM: ["ASM", "American Samoa"],
    AD: ["AND", "Andorra"],
    AND: ["AND", "Andorra"],
    AO: ["AGO", "Angola"],
    AGO: ["AGO", "Angola"],
    AI: ["AIA", "Anguilla"],
    AIA: ["AIA", "Anguilla"],
    AQ: ["ATA", "Antarctica"],
    ATA: ["ATA", "Antarctica"],
    AG: ["ATG", "Antigua and Barbuda"],
    ATG: ["ATG", "Antigua and Barbuda"],
    AR: ["ARG", "Argentina"],
    ARG: ["ARG", "Argentina"],
    AM: ["ARM", "Armenia"],
    ARM: ["ARM", "Armenia"],
    AW: ["ABW", "Aruba"],
    ABW: ["ABW", "Aruba"],
    AU: ["AUS", "Australia"],
    AUS: ["AUS", "Australia"],
    AT: ["AUT", "Austria"],
    AUT: ["AUT", "Austria"],
    AZ: ["AZE", "Azerbaijan"],
    AZE: ["AZE", "Azerbaijan"],
    BS: ["BHS", "Bahamas (the)"],
    BHS: ["BHS", "Bahamas (the)"],
    BH: ["BHR", "Bahrain"],
    BHR: ["BHR", "Bahrain"],
    BD: ["BGD", "Bangladesh"],
    BGD: ["BGD", "Bangladesh"],
    BB: ["BRB", "Barbados"],
    BRB: ["BRB", "Barbados"],
    BY: ["BLR", "Belarus"],
    BLR: ["BLR", "Belarus"],
    BE: ["BEL", "Belgium"],
    BEL: ["BEL", "Belgium"],
    BZ: ["BLZ", "Belize"],
    BLZ: ["BLZ", "Belize"],
    BJ: ["BEN", "Benin"],
    BEN: ["BEN", "Benin"],
    BM: ["BMU", "Bermuda"],
    BMU: ["BMU", "Bermuda"],
    BT: ["BTN", "Bhutan"],
    BTN: ["BTN", "Bhutan"],
    BO: ["BOL", "Bolivia (Plurinational State of)"],
    BOL: ["BOL", "Bolivia (Plurinational State of)"],
    BQ: ["BES", "Bonaire, Sint Eustatius and Saba"],
    BES: ["BES", "Bonaire, Sint Eustatius and Saba"],
    BA: ["BIH", "Bosnia and Herzegovina"],
    BIH: ["BIH", "Bosnia and Herzegovina"],
    BW: ["BWA", "Botswana"],
    BWA: ["BWA", "Botswana"],
    BV: ["BVT", "Bouvet Island"],
    BVT: ["BVT", "Bouvet Island"],
    BR: ["BRA", "Brazil"],
    BRA: ["BRA", "Brazil"],
    IO: ["IOT", "British Indian Ocean Territory (the)"],
    IOT: ["IOT", "British Indian Ocean Territory (the)"],
    BN: ["BRN", "Brunei Darussalam"],
    BRN: ["BRN", "Brunei Darussalam"],
    BG: ["BGR", "Bulgaria"],
    BGR: ["BGR", "Bulgaria"],
    BF: ["BFA", "Burkina Faso"],
    BFA: ["BFA", "Burkina Faso"],
    BI: ["BDI", "Burundi"],
    BDI: ["BDI", "Burundi"],
    CV: ["CPV", "Cabo Verde"],
    CPV: ["CPV", "Cabo Verde"],
    KH: ["KHM", "Cambodia"],
    KHM: ["KHM", "Cambodia"],
    CM: ["CMR", "Cameroon"],
    CMR: ["CMR", "Cameroon"],
    CA: ["CAN", "Canada"],
    CAN: ["CAN", "Canada"],
    KY: ["CYM", "Cayman Islands (the)"],
    CYM: ["CYM", "Cayman Islands (the)"],
    CF: ["CAF", "Central African Republic (the)"],
    CAF: ["CAF", "Central African Republic (the)"],
    TD: ["TCD", "Chad"],
    TCD: ["TCD", "Chad"],
    CL: ["CHL", "Chile"],
    CHL: ["CHL", "Chile"],
    CN: ["CHN", "China"],
    CHN: ["CHN", "China"],
    CX: ["CXR", "Christmas Island"],
    CXR: ["CXR", "Christmas Island"],
    CC: ["CCK", "Cocos (Keeling) Islands (the)"],
    CCK: ["CCK", "Cocos (Keeling) Islands (the)"],
    CO: ["COL", "Colombia"],
    COL: ["COL", "Colombia"],
    KM: ["COM", "Comoros (the)"],
    COM: ["COM", "Comoros (the)"],
    CD: ["COD", "Congo (the Democratic Republic of the)"],
    COD: ["COD", "Congo (the Democratic Republic of the)"],
    CG: ["COG", "Congo (the)"],
    COG: ["COG", "Congo (the)"],
    CK: ["COK", "Cook Islands (the)"],
    COK: ["COK", "Cook Islands (the)"],
    CR: ["CRI", "Costa Rica"],
    CRI: ["CRI", "Costa Rica"],
    HR: ["HRV", "Croatia"],
    HRV: ["HRV", "Croatia"],
    CU: ["CUB", "Cuba"],
    CUB: ["CUB", "Cuba"],
    CW: ["CUW", "Curaçao"],
    CUW: ["CUW", "Curaçao"],
    CY: ["CYP", "Cyprus"],
    CYP: ["CYP", "Cyprus"],
    CZ: ["CZE", "Czechia"],
    CZE: ["CZE", "Czechia"],
    CI: ["CIV", "Côte d'Ivoire"],
    CIV: ["CIV", "Côte d'Ivoire"],
    DK: ["DNK", "Denmark"],
    DNK: ["DNK", "Denmark"],
    DJ: ["DJI", "Djibouti"],
    DJI: ["DJI", "Djibouti"],
    DM: ["DMA", "Dominica"],
    DMA: ["DMA", "Dominica"],
    DO: ["DOM", "Dominican Republic (the)"],
    DOM: ["DOM", "Dominican Republic (the)"],
    EC: ["ECU", "Ecuador"],
    ECU: ["ECU", "Ecuador"],
    EG: ["EGY", "Egypt"],
    EGY: ["EGY", "Egypt"],
    SV: ["SLV", "El Salvador"],
    SLV: ["SLV", "El Salvador"],
    GQ: ["GNQ", "Equatorial Guinea"],
    GNQ: ["GNQ", "Equatorial Guinea"],
    ER: ["ERI", "Eritrea"],
    ERI: ["ERI", "Eritrea"],
    EE: ["EST", "Estonia"],
    EST: ["EST", "Estonia"],
    SZ: ["SWZ", "Eswatini"],
    SWZ: ["SWZ", "Eswatini"],
    ET: ["ETH", "Ethiopia"],
    ETH: ["ETH", "Ethiopia"],
    FK: ["FLK", "Falkland Islands (the) [Malvinas]"],
    FLK: ["FLK", "Falkland Islands (the) [Malvinas]"],
    FO: ["FRO", "Faroe Islands (the)"],
    FRO: ["FRO", "Faroe Islands (the)"],
    FJ: ["FJI", "Fiji"],
    FJI: ["FJI", "Fiji"],
    FI: ["FIN", "Finland"],
    FIN: ["FIN", "Finland"],
    FR: ["FRA", "France"],
    FRA: ["FRA", "France"],
    GF: ["GUF", "French Guiana"],
    GUF: ["GUF", "French Guiana"],
    PF: ["PYF", "French Polynesia"],
    PYF: ["PYF", "French Polynesia"],
    TF: ["ATF", "French Southern Territories (the)"],
    ATF: ["ATF", "French Southern Territories (the)"],
    GA: ["GAB", "Gabon"],
    GAB: ["GAB", "Gabon"],
    GM: ["GMB", "Gambia (the)"],
    GMB: ["GMB", "Gambia (the)"],
    GE: ["GEO", "Georgia"],
    GEO: ["GEO", "Georgia"],
    DE: ["DEU", "Germany"],
    DEU: ["DEU", "Germany"],
    GH: ["GHA", "Ghana"],
    GHA: ["GHA", "Ghana"],
    GI: ["GIB", "Gibraltar"],
    GIB: ["GIB", "Gibraltar"],
    GR: ["GRC", "Greece"],
    GRC: ["GRC", "Greece"],
    GL: ["GRL", "Greenland"],
    GRL: ["GRL", "Greenland"],
    GD: ["GRD", "Grenada"],
    GRD: ["GRD", "Grenada"],
    GP: ["GLP", "Guadeloupe"],
    GLP: ["GLP", "Guadeloupe"],
    GU: ["GUM", "Guam"],
    GUM: ["GUM", "Guam"],
    GT: ["GTM", "Guatemala"],
    GTM: ["GTM", "Guatemala"],
    GG: ["GGY", "Guernsey"],
    GGY: ["GGY", "Guernsey"],
    GN: ["GIN", "Guinea"],
    GIN: ["GIN", "Guinea"],
    GW: ["GNB", "Guinea-Bissau"],
    GNB: ["GNB", "Guinea-Bissau"],
    GY: ["GUY", "Guyana"],
    GUY: ["GUY", "Guyana"],
    HT: ["HTI", "Haiti"],
    HTI: ["HTI", "Haiti"],
    HM: ["HMD", "Heard Island and McDonald Islands"],
    HMD: ["HMD", "Heard Island and McDonald Islands"],
    VA: ["VAT", "Holy See (the)"],
    VAT: ["VAT", "Holy See (the)"],
    HN: ["HND", "Honduras"],
    HND: ["HND", "Honduras"],
    HK: ["HKG", "Hong Kong"],
    HKG: ["HKG", "Hong Kong"],
    HU: ["HUN", "Hungary"],
    HUN: ["HUN", "Hungary"],
    IS: ["ISL", "Iceland"],
    ISL: ["ISL", "Iceland"],
    IN: ["IND", "India"],
    IND: ["IND", "India"],
    ID: ["IDN", "Indonesia"],
    IDN: ["IDN", "Indonesia"],
    IR: ["IRN", "Iran (Islamic Republic of)"],
    IRN: ["IRN", "Iran (Islamic Republic of)"],
    IQ: ["IRQ", "Iraq"],
    IRQ: ["IRQ", "Iraq"],
    IE: ["IRL", "Ireland"],
    IRL: ["IRL", "Ireland"],
    IM: ["IMN", "Isle of Man"],
    IMN: ["IMN", "Isle of Man"],
    IL: ["ISR", "Israel"],
    ISR: ["ISR", "Israel"],
    IT: ["ITA", "Italy"],
    ITA: ["ITA", "Italy"],
    JM: ["JAM", "Jamaica"],
    JAM: ["JAM", "Jamaica"],
    JP: ["JPN", "Japan"],
    JPN: ["JPN", "Japan"],
    JE: ["JEY", "Jersey"],
    JEY: ["JEY", "Jersey"],
    JO: ["JOR", "Jordan"],
    JOR: ["JOR", "Jordan"],
    KZ: ["KAZ", "Kazakhstan"],
    KAZ: ["KAZ", "Kazakhstan"],
    KE: ["KEN", "Kenya"],
    KEN: ["KEN", "Kenya"],
    KI: ["KIR", "Kiribati"],
    KIR: ["KIR", "Kiribati"],
    KP: ["PRK", "Korea (the Democratic People's Republic of)"],
    PRK: ["PRK", "Korea (the Democratic People's Republic of)"],
    KR: ["KOR", "Korea (the Republic of)"],
    KOR: ["KOR", "Korea (the Republic of)"],
    KW: ["KWT", "Kuwait"],
    KWT: ["KWT", "Kuwait"],
    KG: ["KGZ", "Kyrgyzstan"],
    KGZ: ["KGZ", "Kyrgyzstan"],
    LA: ["LAO", "Lao People's Democratic Republic (the)"],
    LAO: ["LAO", "Lao People's Democratic Republic (the)"],
    LV: ["LVA", "Latvia"],
    LVA: ["LVA", "Latvia"],
    LB: ["LBN", "Lebanon"],
    LBN: ["LBN", "Lebanon"],
    LS: ["LSO", "Lesotho"],
    LSO: ["LSO", "Lesotho"],
    LR: ["LBR", "Liberia"],
    LBR: ["LBR", "Liberia"],
    LY: ["LBY", "Libya"],
    LBY: ["LBY", "Libya"],
    LI: ["LIE", "Liechtenstein"],
    LIE: ["LIE", "Liechtenstein"],
    LT: ["LTU", "Lithuania"],
    LTU: ["LTU", "Lithuania"],
    LU: ["LUX", "Luxembourg"],
    LUX: ["LUX", "Luxembourg"],
    MO: ["MAC", "Macao"],
    MAC: ["MAC", "Macao"],
    MG: ["MDG", "Madagascar"],
    MDG: ["MDG", "Madagascar"],
    MW: ["MWI", "Malawi"],
    MWI: ["MWI", "Malawi"],
    MY: ["MYS", "Malaysia"],
    MYS: ["MYS", "Malaysia"],
    MV: ["MDV", "Maldives"],
    MDV: ["MDV", "Maldives"],
    ML: ["MLI", "Mali"],
    MLI: ["MLI", "Mali"],
    MT: ["MLT", "Malta"],
    MLT: ["MLT", "Malta"],
    MH: ["MHL", "Marshall Islands (the)"],
    MHL: ["MHL", "Marshall Islands (the)"],
    MQ: ["MTQ", "Martinique"],
    MTQ: ["MTQ", "Martinique"],
    MR: ["MRT", "Mauritania"],
    MRT: ["MRT", "Mauritania"],
    MU: ["MUS", "Mauritius"],
    MUS: ["MUS", "Mauritius"],
    YT: ["MYT", "Mayotte"],
    MYT: ["MYT", "Mayotte"],
    MX: ["MEX", "Mexico"],
    MEX: ["MEX", "Mexico"],
    FM: ["FSM", "Micronesia (Federated States of)"],
    FSM: ["FSM", "Micronesia (Federated States of)"],
    MD: ["MDA", "Moldova (the Republic of)"],
    MDA: ["MDA", "Moldova (the Republic of)"],
    MC: ["MCO", "Monaco"],
    MCO: ["MCO", "Monaco"],
    MN: ["MNG", "Mongolia"],
    MNG: ["MNG", "Mongolia"],
    ME: ["MNE", "Montenegro"],
    MNE: ["MNE", "Montenegro"],
    MS: ["MSR", "Montserrat"],
    MSR: ["MSR", "Montserrat"],
    MA: ["MAR", "Morocco"],
    MAR: ["MAR", "Morocco"],
    MZ: ["MOZ", "Mozambique"],
    MOZ: ["MOZ", "Mozambique"],
    MM: ["MMR", "Myanmar"],
    MMR: ["MMR", "Myanmar"],
    NA: ["NAM", "Namibia"],
    NAM: ["NAM", "Namibia"],
    NR: ["NRU", "Nauru"],
    NRU: ["NRU", "Nauru"],
    NP: ["NPL", "Nepal"],
    NPL: ["NPL", "Nepal"],
    NL: ["NLD", "Netherlands (the)"],
    NLD: ["NLD", "Netherlands (the)"],
    NC: ["NCL", "New Caledonia"],
    NCL: ["NCL", "New Caledonia"],
    NZ: ["NZL", "New Zealand"],
    NZL: ["NZL", "New Zealand"],
    NI: ["NIC", "Nicaragua"],
    NIC: ["NIC", "Nicaragua"],
    NE: ["NER", "Niger (the)"],
    NER: ["NER", "Niger (the)"],
    NG: ["NGA", "Nigeria"],
    NGA: ["NGA", "Nigeria"],
    NU: ["NIU", "Niue"],
    NIU: ["NIU", "Niue"],
    NF: ["NFK", "Norfolk Island"],
    NFK: ["NFK", "Norfolk Island"],
    MP: ["MNP", "Northern Mariana Islands (the)"],
    MNP: ["MNP", "Northern Mariana Islands (the)"],
    NO: ["NOR", "Norway"],
    NOR: ["NOR", "Norway"],
    OM: ["OMN", "Oman"],
    OMN: ["OMN", "Oman"],
    PK: ["PAK", "Pakistan"],
    PAK: ["PAK", "Pakistan"],
    PW: ["PLW", "Palau"],
    PLW: ["PLW", "Palau"],
    PS: ["PSE", "Palestine, State of"],
    PSE: ["PSE", "Palestine, State of"],
    PA: ["PAN", "Panama"],
    PAN: ["PAN", "Panama"],
    PG: ["PNG", "Papua New Guinea"],
    PNG: ["PNG", "Papua New Guinea"],
    PY: ["PRY", "Paraguay"],
    PRY: ["PRY", "Paraguay"],
    PE: ["PER", "Peru"],
    PER: ["PER", "Peru"],
    PH: ["PHL", "Philippines (the)"],
    PHL: ["PHL", "Philippines (the)"],
    PN: ["PCN", "Pitcairn"],
    PCN: ["PCN", "Pitcairn"],
    PL: ["POL", "Poland"],
    POL: ["POL", "Poland"],
    PT: ["PRT", "Portugal"],
    PRT: ["PRT", "Portugal"],
    PR: ["PRI", "Puerto Rico"],
    PRI: ["PRI", "Puerto Rico"],
    QA: ["QAT", "Qatar"],
    QAT: ["QAT", "Qatar"],
    MK: ["MKD", "Republic of North Macedonia"],
    MKD: ["MKD", "Republic of North Macedonia"],
    RO: ["ROU", "Romania"],
    ROU: ["ROU", "Romania"],
    RU: ["RUS", "Russian Federation (the)"],
    RUS: ["RUS", "Russian Federation (the)"],
    RW: ["RWA", "Rwanda"],
    RWA: ["RWA", "Rwanda"],
    RE: ["REU", "Réunion"],
    REU: ["REU", "Réunion"],
    BL: ["BLM", "Saint Barthélemy"],
    BLM: ["BLM", "Saint Barthélemy"],
    SH: ["SHN", "Saint Helena, Ascension and Tristan da Cunha"],
    SHN: ["SHN", "Saint Helena, Ascension and Tristan da Cunha"],
    KN: ["KNA", "Saint Kitts and Nevis"],
    KNA: ["KNA", "Saint Kitts and Nevis"],
    LC: ["LCA", "Saint Lucia"],
    LCA: ["LCA", "Saint Lucia"],
    MF: ["MAF", "Saint Martin (French part)"],
    MAF: ["MAF", "Saint Martin (French part)"],
    PM: ["SPM", "Saint Pierre and Miquelon"],
    SPM: ["SPM", "Saint Pierre and Miquelon"],
    VC: ["VCT", "Saint Vincent and the Grenadines"],
    VCT: ["VCT", "Saint Vincent and the Grenadines"],
    WS: ["WSM", "Samoa"],
    WSM: ["WSM", "Samoa"],
    SM: ["SMR", "San Marino"],
    SMR: ["SMR", "San Marino"],
    ST: ["STP", "Sao Tome and Principe"],
    STP: ["STP", "Sao Tome and Principe"],
    SA: ["SAU", "Saudi Arabia"],
    SAU: ["SAU", "Saudi Arabia"],
    SN: ["SEN", "Senegal"],
    SEN: ["SEN", "Senegal"],
    RS: ["SRB", "Serbia"],
    SRB: ["SRB", "Serbia"],
    SC: ["SYC", "Seychelles"],
    SYC: ["SYC", "Seychelles"],
    SL: ["SLE", "Sierra Leone"],
    SLE: ["SLE", "Sierra Leone"],
    SG: ["SGP", "Singapore"],
    SGP: ["SGP", "Singapore"],
    SX: ["SXM", "Sint Maarten (Dutch part)"],
    SXM: ["SXM", "Sint Maarten (Dutch part)"],
    SK: ["SVK", "Slovakia"],
    SVK: ["SVK", "Slovakia"],
    SI: ["SVN", "Slovenia"],
    SVN: ["SVN", "Slovenia"],
    SB: ["SLB", "Solomon Islands"],
    SLB: ["SLB", "Solomon Islands"],
    SO: ["SOM", "Somalia"],
    SOM: ["SOM", "Somalia"],
    ZA: ["ZAF", "South Africa"],
    ZAF: ["ZAF", "South Africa"],
    GS: ["SGS", "South Georgia and the South Sandwich Islands"],
    SGS: ["SGS", "South Georgia and the South Sandwich Islands"],
    SS: ["SSD", "South Sudan"],
    SSD: ["SSD", "South Sudan"],
    ES: ["ESP", "Spain"],
    ESP: ["ESP", "Spain"],
    LK: ["LKA", "Sri Lanka"],
    LKA: ["LKA", "Sri Lanka"],
    SD: ["SDN", "Sudan (the)"],
    SDN: ["SDN", "Sudan (the)"],
    SR: ["SUR", "Suriname"],
    SUR: ["SUR", "Suriname"],
    SJ: ["SJM", "Svalbard and Jan Mayen"],
    SJM: ["SJM", "Svalbard and Jan Mayen"],
    SE: ["SWE", "Sweden"],
    SWE: ["SWE", "Sweden"],
    CH: ["CHE", "Switzerland"],
    CHE: ["CHE", "Switzerland"],
    SY: ["SYR", "Syrian Arab Republic"],
    SYR: ["SYR", "Syrian Arab Republic"],
    TW: ["TWN", "Taiwan (Province of China)"],
    TWN: ["TWN", "Taiwan (Province of China)"],
    TJ: ["TJK", "Tajikistan"],
    TJK: ["TJK", "Tajikistan"],
    TZ: ["TZA", "Tanzania, United Republic of"],
    TZA: ["TZA", "Tanzania, United Republic of"],
    TH: ["THA", "Thailand"],
    THA: ["THA", "Thailand"],
    TL: ["TLS", "Timor-Leste"],
    TLS: ["TLS", "Timor-Leste"],
    TG: ["TGO", "Togo"],
    TGO: ["TGO", "Togo"],
    TK: ["TKL", "Tokelau"],
    TKL: ["TKL", "Tokelau"],
    TO: ["TON", "Tonga"],
    TON: ["TON", "Tonga"],
    TT: ["TTO", "Trinidad and Tobago"],
    TTO: ["TTO", "Trinidad and Tobago"],
    TN: ["TUN", "Tunisia"],
    TUN: ["TUN", "Tunisia"],
    TR: ["TUR", "Turkey"],
    TUR: ["TUR", "Turkey"],
    TM: ["TKM", "Turkmenistan"],
    TKM: ["TKM", "Turkmenistan"],
    TC: ["TCA", "Turks and Caicos Islands (the)"],
    TCA: ["TCA", "Turks and Caicos Islands (the)"],
    TV: ["TUV", "Tuvalu"],
    TUV: ["TUV", "Tuvalu"],
    UG: ["UGA", "Uganda"],
    UGA: ["UGA", "Uganda"],
    UA: ["UKR", "Ukraine"],
    UKR: ["UKR", "Ukraine"],
    AE: ["ARE", "United Arab Emirates (the)"],
    ARE: ["ARE", "United Arab Emirates (the)"],
    GB: ["GBR", "United Kingdom of Great Britain and Northern Ireland (the)"],
    GBR: ["GBR", "United Kingdom of Great Britain and Northern Ireland (the)"],
    UM: ["UMI", "United States Minor Outlying Islands (the)"],
    UMI: ["UMI", "United States Minor Outlying Islands (the)"],
    US: ["USA", "United States of America (the)"],
    USA: ["USA", "United States of America (the)"],
    UY: ["URY", "Uruguay"],
    URY: ["URY", "Uruguay"],
    UZ: ["UZB", "Uzbekistan"],
    UZB: ["UZB", "Uzbekistan"],
    VU: ["VUT", "Vanuatu"],
    VUT: ["VUT", "Vanuatu"],
    VE: ["VEN", "Venezuela (Bolivarian Republic of)"],
    VEN: ["VEN", "Venezuela (Bolivarian Republic of)"],
    VN: ["VNM", "Viet Nam"],
    VNM: ["VNM", "Viet Nam"],
    VG: ["VGB", "Virgin Islands (British)"],
    VGB: ["VGB", "Virgin Islands (British)"],
    VI: ["VIR", "Virgin Islands (U.S.)"],
    VIR: ["VIR", "Virgin Islands (U.S.)"],
    WF: ["WLF", "Wallis and Futuna"],
    WLF: ["WLF", "Wallis and Futuna"],
    EH: ["ESH", "Western Sahara"],
    ESH: ["ESH", "Western Sahara"],
    YE: ["YEM", "Yemen"],
    YEM: ["YEM", "Yemen"],
    ZM: ["ZMB", "Zambia"],
    ZMB: ["ZMB", "Zambia"],
    ZW: ["ZWE", "Zimbabwe"],
    ZWE: ["ZWE", "Zimbabwe"],
    AX: ["ALA", "Åland Islands"],
    ALA: ["ALA", "Åland Islands"],
};
