[features]
seeds = false
skip-lint = false
[programs.localnet]
christmas_web3 = "5ZohsZtvVnjLy7TZDuujXneojE8dq27Y4mrsq3e8eKTZ"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/Users/benjaminhon/Developer/christmas/id_local.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
